services:
  plena_finance_backend:
    image: user-management-microservice
    container_name: plena-finance-backend
    restart: unless-stopped
    build:
      context: ./UserMicroService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
      - ./UserMicroService:/app
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    container_name: plena-finance-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rtrp
      - MONGO_INITDB_ROOT_PASSWORD=Qwerty@12
    ports:
      - "8001:27017"
    volumes:
      - plena-finance:/data/db
    networks:
      - app_network
    # healthcheck:
    #   test: ['CMD-SHELL', 'mongosh', '--eval', "db.runCommand('ping').ok"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s

  redis:
    container_name: plena-finance-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "8002:8002"
      - "6379:6379"
    volumes:
      - plena-finance:/data/cache
    depends_on:
      - mongodb
    environment:
      - HOST=plena-finance-redis
      - PORT=6379
    networks:
      - app_network

volumes:
  plena-finance_backend-backend:
  plena-finance:

networks:
  app_network:
    driver: bridge
